### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by phyomawko** [raj-71/supply-chain-fabric#1]
when I access localhost:4000, the following messages appeared in browser.
UnauthorizedError: No authorization token was found
    at middleware (/home/phyo/supply-chain-fabric/backend/node_modules/express-jwt/lib/index.js:76:21)
    at /home/phyo/supply-chain-fabric/backend/node_modules/express-unless/index.js:47:5
    at Layer.handle [as handle_request] (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/index.js:328:13)
    at /home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/index.js:346:12)
    at next (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/home/phyo/supply-chain-fabric/backend/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/phyo/supply-chain-fabric/backend/node_modules/express/lib/router/index.js:328:13)

**Comment by MyatHtetKyaw** [comment]
I have faced this error too

**Comment by raj-71** [comment]
Apologies for the late reply, for Authorization Error I have mentioned in the Troubleshooting this problem in Point 7 and 8, depending on the Error Code you can refer to that.

**Comment by im-ukr77** [comment]
> Apologies for the late reply, for Authorization Error I have mentioned in the Troubleshooting this problem in Point 7 and 8, depending on the Error Code you can refer to that.

tried both yet the issue persists, any other potential fix which you could provide for authorization issue?
